# 연습문제 01 - 신경망 기초

In [1]:
import numpy as np
y = np.array([[0.1, 0.2, 0.7], [0.2, 0.8, 0.1]])
print(y)
print(np.argmax(y, axis=0))
print(np.argmax(y, axis=1))

[[0.1 0.2 0.7]
 [0.2 0.8 0.1]]
[1 1 0]
[2 1]


In [3]:

import numpy as np

y1 = np.array([0.2, 0.1, 0.2, 0.5])
y2 = np.array([0.1, 0.1, 0.1, 0.7])
t   = np.array([0,   0,   0,  1])

print(np.log(y1).round(2))   
print(np.log(y2).round(2))  

print(-t * np.log(y1).round(2))  
print(-t * np.log(y2).round(2))   

print(np.sum(-t * np.log(y1)).round(2))   
print(np.sum(-t * np.log(y2)).round(2))   

cee1 = np.sum(-np.log(0.5)).round(2)
cee2 = np.sum(-np.log(0.7)).round(2)

print(cee1)   
print(cee2)   

print(-np.log(0.5).round(2))   
print(-np.log(0.7).round(2))  

[-1.61 -2.3  -1.61 -0.69]
[-2.3  -2.3  -2.3  -0.36]
[-0.   -0.   -0.    0.69]
[-0.   -0.   -0.    0.36]
0.69
0.36
0.69
0.36
0.69
0.36


In [4]:
import numpy as np

def softmax(x):
    x = x - np.max(x, axis=1).reshape(-1,1)
    return np.exp(x) / np.sum(np.exp(x), axis=1).reshape(-1,1)

t = np.array([1, 0, 2, 1])
a3 = np.array([[0.1, 0.7, 0.1], [0.6, 0.2, 0.3], [0.8, 0.2, 0.1], [0.2, 0.6, 0.3]])
y = softmax(a3)              # 예측 확률
p = np.argmax(y, axis=1)       # 예측 인덱스
print(a3)
print(y.round(3))
print(p)
print(t)

accuracy_cnt = 0                 # 정확하게 예측한 개수
for i in range(len(y)):
    if p[i] == t[i]: accuracy_cnt += 1

print(f"Accuracy = {accuracy_cnt / len(y)}")  # 예측 정확도

[[0.1 0.7 0.1]
 [0.6 0.2 0.3]
 [0.8 0.2 0.1]
 [0.2 0.6 0.3]]
[[0.262 0.477 0.262]
 [0.415 0.278 0.307]
 [0.489 0.268 0.243]
 [0.278 0.415 0.307]]
[1 0 0 1]
[1 0 2 1]
Accuracy = 0.75


In [6]:
import numpy as np
np.random.seed(42)

x = np.array([[1, 2, 1, 3, 2], [2, 5, 3, 4, 1]])
dropout_ratio = 0.3
p = np.random.rand(*x.shape)
mask = p > dropout_ratio
x_drop = x * mask

print(x)
print(p.round(3))
print(mask)
print(x_drop)

[[1 2 1 3 2]
 [2 5 3 4 1]]
[[0.375 0.951 0.732 0.599 0.156]
 [0.156 0.058 0.866 0.601 0.708]]
[[ True  True  True  True False]
 [False False  True  True  True]]
[[1 2 1 3 0]
 [0 0 3 4 1]]
